trigger: 
- main

pool: 
   vmImage: windows

jobs:
- deployment: hugo
  displayName: Deploy to VM
  environment: 
   name: ranorex
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"
            - task: CmdLine@2
              inputs:
                script: |
                  echo Write your commands here
                  
                  echo Hello world

            - task: PowerShell@2
              inputs:
               targetType: 'inline'
               script: |
                # Write your PowerShell commands here.
                
                Write-Host "Hello World"
                Get-ChildItem -Path C:\WindowsAzure\Logs
                # Predefined Variables
                $adSdkUrl = "https://storagename.blob.core.windows.net/prelabelcont/RanorexRemoteAgent-7.3.0.msi"
                $adSdkPath = Join-Path $env:TEMP "RanorexRemoteAgent-7.3.0.msi"
                
 
                # Download the files to local temp folder
                Write-Output "downloading $adSdkUrl…"
                Invoke-WebRequest -Uri $adSdkUrl -OutFile $adSDKPath 
                # Install the SDKs (use the "qn" flag to install silently)
                Write-Output "installing $adSdkPath…"
                Start-Process $adSdkPath -ArgumentList "/q" -Wait
                Write-Output " start Ranorex Agent"
                $RanorexAgent  = "C:\Program Files (x86)\Ranorex\Agent\RanorexRemoteAgent"
                #Start-Process $RanorexAgent  "/qn"   -Wait
                #Start TestCase assuming Testagent is running
                Start-Process C:\Users\hugo\Documents\GitHub\mytest1\MyTest1\mytest1.exe /agent:MyAgent

                  

