trigger: 
- main

pool: 
   vmImage: windows

jobs:
- deployment: hugo
  displayName: Deploy to VM
  environment: 
   name: ranorex
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"
            - task: CmdLine@2
              inputs:
                script: |
                  echo Write your commands here
                  
                  echo Hello world

