variables:
- name: BuildParameters.solution
  value: '**\*.sln'
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Prelabel_PoC
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 4.4.1
    inputs:
      versionSpec: 4.4.1
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: $(BuildParameters.solution)
  - task: VSBuild@1
    displayName: Build solution **\*.sln
    condition: succeededOrFailed()
    inputs:
      solution: $(BuildParameters.solution)
  - task: CmdLine@2
    displayName: Ranorex_prelabel_execution
    inputs:
      script: $(System.DefaultWorkingDirectory)\mytest1\MyTest1\bin\Debug\MyTest1.exe /m /junit /zr /zrf:Reports/Reprtforbuild.rxlog
  - task: VisualStudioTestPlatformInstaller@1
    displayName: Visual Studio Test Platform Installer
    continueOnError: True
  - task: VSTest@2
    displayName: VsTest - testAssemblies
    condition: succeededOrFailed()
    enabled: False
    inputs:
      testAssemblyVer2: >-
        **\$(BuildConfiguration)\*test*.dll

        !**\obj\**
      vsTestVersion: toolsInstaller
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    enabled: False
  - task: PublishSymbols@2
    displayName: Publish symbols path
    continueOnError: True
    inputs:
      SearchPattern: '**\bin\**\*.pdb'
      PublishSymbols: false
      SymbolServerType: TeamServices
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**\bin\$(BuildConfiguration)\**'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: Ranorex report
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(System.DefaultWorkingDirectory)\Reports\
      ArtifactName: Ranorex report
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
  - task: PublishTestResults@2
    displayName: Publish Ranorex Test Results
    inputs:
      testResultsFiles: '**/*.xml'
...
