trigger: 
- main

pool: 
   vmImage: windows

jobs:
- deployment: hugo
  displayName: Deploy to VM
  environment: 
   name: ranorex
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"
            - task: CmdLine@2
              inputs:
                script: |
                  echo Write your commands here
                  
                  echo Hello world
                  - task: PowerShellOnTargetMachines@3
                    inputs:
                      InlineScript: |
                        # Write your powershell commands here.
                        
                        Write-Output "Hello World"

