trigger: 
- main

pool: 
   vmImage: windows-2019

variables:
  subscriptionId: 'd8cd2f9e-2816-4fe8-b17e-82f9204cab2e'
  azureResourceManagerConnection: 'prod100'
  storageAccountName: 'prod100'
  storageAccountConnectionString: $STORAGECONNECTIONSTRING
  containerName: templates$(Build.BuildId)
  tool : https://prod100.blob.core.windows.net/test/AUDIPrelabelTool_Setup_1.8.2.1222.exe

stages:
- stage: 'VM'
  jobs:
  - deployment: VMDeploy
    displayName: 'Deploy to VM'
    environment: 
      name: Ranorex
      resourceType: VirtualMachine
    strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"


   
  - job: 'SetupInfra'
    steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo $(STORAGECONNECTIONSTRING)
            echo 'ARTIFACT STAGING DIRECTORY'
            echo $(build.artifactstagingdirectory)
            echo $(Build.BuildId)
            echo H e l l o w o r l d
            echo $(build.artifactstagingdirectory)\${{ variables.containerName }}
            echo $(System.DefaultWorkingDirectory)
      - task: CopyFiles@2
        displayName: 'Copy composing to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: 'mytest1'
          Contents:  
            '**/*'
            
          TargetFolder: '$(build.artifactstagingdirectory)\${{variables.containerName}}'
      - task: CmdLine@2
        inputs:
          script: |
            echo  $(build.artifactstagingdirectory)\${{ variables.containerName }}
            dir $(build.artifactstagingdirectory)\${{ variables.containerName }}
            dir $(System.DefaultWorkingDirectory)
            echo System default working directory
            echo $(System.DefaultWorkingDirectory) 
            dir $(System.DefaultWorkingDirectory) 
            echo TargetFolder

      - task: AzureCLI@2
        displayName: "Create container $(Build.BuildId)"
        inputs:
          azureSubscription: ${{ variables.azureResourceManagerConnection }}
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage container create --connection-string "${{ variables.storageAccountConnectionString }}" -n ${{ variables.containerName }} --account-name ${{ variables.storageAccountName }}'
      - task: AzureCLI@2
        inputs:
          azureSubscription: '${{ variables.azureResourceManagerConnection }}'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob upload-batch --account-name ${{ variables.storageAccountName }} -d ${{ variables.containerName }} -s ./mytest1 --connection-string "${{ variables.storageAccountConnectionString }}"'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

      - task: CmdLine@2
        displayName: Ranorex_prelabel_execution
        inputs:
          script: 
           #$(System.DefaultWorkingDirectory)\MyTest1\bin\Debug\MyTest1.exe /m /junit /zr /zrf:Reports/Reprtforbuild.rxlog
           msiexec /i $(System.DefaultWorkingDirectory)\MyTest1\RanorexRemoteAgent-7.3.0.msi /quiet

      - task: CmdLine@2
        displayName: TestExecution
        inputs:
          script: |
            echo TestExecution 
            $(System.DefaultWorkingDirectory)\MyTest1\bin\Debug\MyTest1.exe / quiet
            echo test execution done
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'


- stage: 'TestResults'
  displayName: 'Test Results'
  jobs: 
    - job: 'Testresults'
      steps:

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.DefaultWorkingDirectory)'
    

